### PR TITLE
Update dependencies and push files

### PR DESCRIPTION
**Pull request by serras**
According to the documentation, bumping the version of `@actions/core` is not enough to fix the `add-path` problem, you also need to push the new files (the entire `node_modules`) to the repo.

### CODE REVIEW

**Comment by serras** [comment]
I've checked this works on a private repo when using my fork.

**Comment by rachelcarmena** [comment]
@serras :raised_hands: :clap: 

Hi @pavpanchekha , this PR actually fixes #4, **confirmed**!! :tada: It's not necessary to version `node_modules` directory in the code repository. It can be added in `.gitignore` because it's created from `package.json` file (where the main change in this case is located).

**Comment by serras** [comment]
According to the [documentation](https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-javascript-action#commit-tag-and-push-your-action-to-github) you really need to add your `node_modules` to your repo or it won't work.

> From your terminal, commit your `action.yml`, `index.js`, **`node_modules`**, `package.json`, `package-lock.json`, and `README.md` files. **If you added a `.gitignore` file that lists node_modules, you'll need to remove that line to commit the `node_modules` directory.**

**Comment by rachelcarmena** [comment]
Oh, ok, it's a requirement by GitHub Actions :+1: Thanks @serras !!

**Comment by pavpanchekha** [comment]
Wasn't totally sure what to do but I merged it. Hope it was right, let me know if it works!

**Comment by rachelcarmena** [comment]
Thanks @pavpanchekha I'm sure it works because we're using a fork by @serras with that change. Please, if a new release is created, we could move to your action again. Thank you so much!!! :raised_hands:

**Comment by rachelcarmena** [comment]
Thanks @pavpanchekha for https://github.com/pavpanchekha/setup-z3/releases/tag/1.2.2. Confirmed!! :+1:  It works :tada:

**Pull request merged**
